name: divorce_party_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5

  google_fonts: ^4.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/party_bg.jpg
    - assets/icons/ic_calendar.png
    - assets/icons/ic_location.png
    - assets/icons/ic_phone.png
    - assets/icons/ic_share.png
    - assets/icons/instagram.png

  fonts:
    - family: PoetsenOne
      fonts:
        - asset: assets/fonts/PoetsenOne-Regular.ttf
          weight: 400